### ISSUE TITLE
Service principal for permission request could not be found

### ISSUE THREAD

**Issue by alan-hu** [microsoftgraph/msgraph-training-spfx#14]
I followed this demo and I can see the graph permission requests in the Pending Approval section in SharePoint admin centre's API Management. However when approving them I encounter the following error:
[HTTP]:400 - [CorrelationId]:8246e09e-6091-0000-2e69-e12349864888 [Version]:16.0.0.8915 - The service principal for permssion request ms-graph-sp-fx-client-side-solution could not be found.

I did some research on this issue but couldn't find a solution. MS Support is not helpful in resolving this issue too. Any advice please?

**Comment by jasonjoh** [comment]
@alan-hu My apologies for the neglect on this issue. This example hasn't been actively maintained for a while now. I'm taking over this repo and will be re-writing the lab using the latest versions. Do you still need assistance with this?
