### ISSUE TITLE
typo in tutorial / 02-create-app.md

### ISSUE THREAD

**Issue by andiHero** [microsoftgraph/msgraph-training-spfx#47]
**Where did you get the code?**
Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)
https://docs.microsoft.com/en-us/graph/tutorials/spfx?tutorial-step=1

**Describe the bug**
In the Tutorial - 02-create-app (Create an SPFX web Part) is a typo in the installation of the dependencies. In the second command you should execute "npm install @microsoft/mgt@2.1.0 date-fns @2.21.1". There is a wrong space here, which causes npm not to recognize the command. The correct command should be "npm install @microsoft/mgt@2.1.0 date-fns@2.21.1".

**To Reproduce**
1. Try to Install dependencies
2. See error

**Desktop (please complete the following information):**
 - npm version 8.0.0

**Comment by jasonjoh** [comment]
Thanks for reporting this. We've discontinued this tutorial, so I'm closing this.
