### ISSUE TITLE
Lab 1 issues:  has no exported member 'MSGraphClient'

### ISSUE THREAD

**Issue by TroyHannon** [microsoftgraph/msgraph-training-spfx#8]
import { MSGraphClient } from '@microsoft/sp-http';

on "gulp build" I get the following errors:
error TS2305: Module '"<my local folders>/node_modules/@microsoft/sp-http/lib/index"' has no exported member 'MSGraphClient'.

Using SPFx 1.6

Note:  as i followed the directions, when I executed "npm install @microsoft/microsoft-graph-types --save-dev"

I got:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @microsoft/microsoft-graph-types@1.5.0
added 1 package and audited 273618 packages in 23.898s
found 410 vulnerabilities (177 low, 28 moderate, 198 high, 7 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Any help would be greatly appreciated!  I have searched many hours trying to find a solution...

**Comment by TroyHannon** [comment]
Adding package.json:
{
  "name": "ms-graph-sp-fx",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.1",
    "@microsoft/sp-lodash-subset": "~1.4.1",
    "@microsoft/sp-webpart-base": "~1.4.1",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "react": "15.6.2",
    "react-dom": "15.6.2"
  },
  "devDependencies": {
    "@microsoft/microsoft-graph-types": "^1.5.0",
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }
}

**Comment by TroyHannon** [comment]
Thanks, I has thought I upgraded to 1.6 already so that never occurred to me, thx!

Troy Hannon
CarMax IT
Recruiting Systems
(804) 747-0422 x3165
[cid:image001.png@01D2B85F.E9F86620]

**Comment by andrewconnell** [comment]
You may have updated the generator, but you still have to update each project.
